services:
  eregulations-mcp:
    build: .
    container_name: eregulations-mcp
    ports:
      - "127.0.0.1:7000:7000"
    environment:
      - NODE_ENV=production
      - EREGULATIONS_API_URL=https://api-tanzania.tradeportal.org
      #- BASE_URL=https://mcp.eregistrations.dev
      - PORT=7000
      - STDIO_CMD="node dist/index.js"
      #- SSE_PATH=/sse
      #- MESSAGE_PATH=/message
      #- HEALTH_ENDPOINT=/health
      #- LOG_LEVEL=info
      #- CORS_ENABLED=true
    restart: unless-stopped

  # Other MCP servers can be added here