services:
  eregulations-mcp:
    build: .
    container_name: eregulations-mcp
    ports:
      - "127.0.0.1:7000:7000"
    env_file:
      - .env
    restart: unless-stopped

  # Other MCP servers can be added here